parameters:
    appventus_mangopay.mango_api.class: "AppVentus\\MangopayBundle\\Helper\\MangopayHelper"
    appventus_mangopay.payment_helper.class: "AppVentus\\MangopayBundle\\Helper\\PaymentHelper"
    appventus_mangopay.card_registration_helper.class: "AppVentus\\MangopayBundle\\Helper\\CardRegistrationHelper"
    appventus_mangopay.payment_direct_helper.class: "AppVentus\\MangopayBundle\\Helper\\PaymentDirectHelper"
    appventus_mangopay.user_helper.class: "AppVentus\\MangopayBundle\\Helper\\UserHelper"
    appventus_mangopay.bank_information_helper.class: "AppVentus\\MangopayBundle\\Helper\\BankInformationHelper"
    appventus_mangopay.wallet_helper.class: "AppVentus\\MangopayBundle\\Helper\\WalletHelper"
    appventus_mangopay.order.class: "AppVentus\\MangopayBundle\\Entity\\Order"
    appventus_mangopay.form.card: "AppVentus\\MangopayBundle\\Form\\CardType"

services:
    appventus_mangopay.mango_api:
        class: %appventus_mangopay.mango_api.class%
        arguments:
            - %appventus_mangopay.client_id%
            - %appventus_mangopay.client_password%
            - %appventus_mangopay.base_url%
            - "@event_dispatcher"
            - "@doctrine.orm.entity_manager"
            - %appventus_mangopay.debug_mode%

    appventus_mangopay.user_helper:
        class: %appventus_mangopay.user_helper.class%
        arguments:
            - @appventus_mangopay.mango_api
            - @doctrine.orm.entity_manager
            - "@event_dispatcher"
    appventus_mangopay.bank_information_helper:
        class: %appventus_mangopay.bank_information_helper.class%
        arguments:
            - @appventus_mangopay.mango_api
            - @doctrine.orm.entity_manager
            - @appventus_mangopay.user_helper
    appventus_mangopay.wallet_helper:
        class: %appventus_mangopay.wallet_helper.class%
        arguments:
            - @appventus_mangopay.mango_api
            - @appventus_mangopay.user_helper
            - @doctrine.orm.entity_manager
            - "@event_dispatcher"
    appventus_mangopay.card_registration_helper:
        class: %appventus_mangopay.card_registration_helper.class%
        arguments:
            - @appventus_mangopay.mango_api
            - @appventus_mangopay.card_registration_helper
            - @doctrine.orm.entity_manager
            - "@event_dispatcher"
    appventus_mangopay.payment_helper:
        class: %appventus_mangopay.payment_helper.class%
        arguments:
            - @appventus_mangopay.mango_api
            - @router
            - "@event_dispatcher"

    appventus_mangopay.payment_direct_helper:
        class: %appventus_mangopay.payment_direct_helper.class%
        arguments:
            - @appventus_mangopay.mango_api
            - @router
            - "@event_dispatcher"

    appventus_mangopay.form.card:
        class: %appventus_mangopay.form.card%
        tags:
            - { name: form.type }
